; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TaskPlanner"
#define MyAppVersion "1.0"
#define MyAppPublisher "МАЗ"
#define MyAppURL "https://maz.by/"
#define MyAppExeName "main.exe"
#define MyAppServerName "TasksServer.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".taskplanner"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. 
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A830364F-AFC0-4B02-A4EF-C2AFD0B2BA0E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Для установки без прав администратора (для текущего пользователя)
PrivilegesRequired=lowest
OutputDir=C:\Users\Victoria\Downloads\Telegram Desktop\Output
OutputBaseFilename=TaskPlannerSetup
SetupIconFile=C:\TaskPlanner\images\taskplanner.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
; ❌ УДАЛЯЕМ строку ниже:
; Name: "servericon"; Description: "Создать ярлык для сервера"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; === КЛИЕНТСКОЕ ПРИЛОЖЕНИЕ (PyInstaller --onedir) ===
; Основной исполняемый файл
Source: "C:\TaskPlanner\dist\main\main.exe"; DestDir: "{app}"; Flags: ignoreversion
; Все остальные файлы из папки main
Source: "C:\TaskPlanner\dist\main\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; === СЕРВЕР (PyInstaller --onefile) ===
Source: "C:\TaskPlanner\dist\TasksServer.exe"; DestDir: "{app}"; Flags: ignoreversion

; ✅ ДОБАВЛЯЕМ РУКОВОДСТВО ПОЛЬЗОВАТЕЛЯ
; Если файл в корне проекта:
Source: "C:\TaskPlanner\presentation.txt"; DestDir: "{app}"; Flags: ignoreversion

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
; ❌ УДАЛЯЕМ строки ниже (ярлыки для сервера):
; Name: "{autodesktop}\TaskPlanner Server"; Filename: "{app}\{#MyAppServerName}"; Tasks: servericon
; Name: "{autoprograms}\TaskPlanner Server"; Filename: "{app}\{#MyAppServerName}"; Tasks: servericon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
; ❌ УДАЛЯЕМ строку ниже (запуск сервера):
; Filename: "{app}\{#MyAppServerName}"; Description: "Запустить сервер TaskPlanner"; Flags: nowait postinstall skipifsilent